### ISSUE TITLE
Failing to find the column name of the coordinate in the env file with the R.package

### ISSUE THREAD

**Issue by Manuel-Derrien** [Sylvie/sambada#24]
Hello, 

I'm trying to run the sambadaParallel with the coordinates of the individuals.
Regardless of the way I input the parameter, the program print me this error : 
`Error in sambadaParallel(genoFile = "blue_file_geno.csv", envFile = "blue_file_env_prepared.csv",  :
  The first two words of spatial parameter should be in header line of envFile`

I'm wondering if there was a bug or is there a specific way to input the col names of these coordinates.
I'm currently trying with this format `"The_longitude The_latitude cartesian gaussian 50000"`.

The full command look like this : 
`sambadaParallel(genoFile="blue_file_geno.csv",
                envFile="blue_file_env_prepared.csv",
                idGeno= "ID_indiv",
                idEnv= "ID_indiv_env",
                outputFile= "result_of_SamBada.csv",
                dimMax = 2,
                cores = 4,
                wordDelim = " ",
                saveType = "END BEST 0.05",
                populationVar = NULL,
                spatial = "The_longitude The_latitude cartesian gaussian 50000",
                autoCorr = NULL,
                shapeFile = NULL,
                colSupEnv = NULL,
                colSupMark = NULL,
                subsetVarEnv = NULL,
                subsetVarMark = NULL,
                headers = TRUE,
                directory = NULL,
                keepAllFiles = TRUE)
`
Replacing "The_longitude The_latitude" by "2 3", their number of columns brings the same error.
The env and geno file has been built by this package.

Hope I did not forget to put some important information about this issue report feel free to ask some more information.

Best regards

**Comment by Sylvie** [comment]
Hello @Manuel-Derrien ,
I hope my answer by mail solved the issue.
Kind regards,
Sylvie
