### ISSUE TITLE
Error v. 0.6.1-windows

### ISSUE THREAD

**Issue by CIWa** [Sylvie/sambada#4]
Hi,
I run into a problem when installing Sambada on my computer:
Program call:
C:\sambada.exe
Incorrect number of arguments
I am using Windows 10.
Is there anything known about the issue?

**Comment by Sylvie** [comment]
Hi @CIWa,
Thanks a lot for your interest in Sambada!
Sorry for the delay, I just saw your message.

Sambada needs some information to launch the analysis.
Generally one provides a parameter file and one or two data files.

Here is an example (starting from the project main directory):
```
cd examples/data-from-manual/two-data-files/
../../../binaries/sambada param.txt env-data.txt mol-data.txt
```
The analysis should not take long and should produce the following files:
- mol-data-Out-0.txt
- mol-data-Out-1.txt
- mol-data-log.txt

This dataset doesn't represent anything. It just an example to illustrate the program use.
The format of the input files and the program launch are presented on pages 6-10 of the manual (Sambadoc.pdf) and the output files are described on pages 15-17.

Does this answer your question?

Kind regards,
Sylvie

**Comment by CIWa** [comment]
Hi @Sylvie,

Thanks a lot for the help! It turns out that I mistakenly thought the sambada.exe was the sambada-installer-exe. Reading helps :) Anyhow, thank you for the clarification, and I look forward to using Sambada!

Best,
Isabel

**Comment by Sylvie** [comment]
Hi Isabel,
Thanks a lot for your feedback!
Happy analysing with Sambada ;-)
Kind regards,
Sylvie
