### ISSUE TITLE
semicolon (;) after if() statement

### ISSUE THREAD

**Issue by fcolecumberri** [Sylvie/sambada#9]
I'm 99.9% sure this is a bug, but since I'm note 100% sure I'm not making a pull request for this,
but in file `src/JournalTemporaire.cpp` line 71~78 you have a semicolon `;` after the `if()`,
since the semicolon ends the "if" statement it doesn't matter if oss is NULL or empty,
it will do `retourLigne();` since it's not part of the "if" statement.
```
JournalTemporaire& JournalTemporaire::synchronise()
{
    if( oss!=NULL && !(oss->str().empty()) );
    {
        retourLigne();
    }
	return *this;
}
```

**Comment by Sylvie** [comment]
Well spotted, it is indeed a bug.
My IDE replaced the `;` by `{}` on my current branch, but it doesn't make more sense.
I will fix it, but I am not sure if I can test it yet.
